service: dDPrueba

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  topsecret:
    handler: src/handlers/POST/topsecret.topSecret
    events:
      - httpApi:
          path: /topsecret
          method: post

  serviceGET:
    handler: src/handlers/GET/handlerGET.serviceGET
    events:
      - httpApi:
          path: /serviceGET
          method: get
