service: dDPrueba

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  topsecret:
    handler: src/handlers/topsecret.topSecret
    events:
      - httpApi:
          path: /topsecret
          method: post
